# Generated by Django 4.0 on 2022-01-23 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.CharField(max_length=10)),
                ('requirements', models.CharField(max_length=50)),
                ('referral_link', models.CharField(max_length=150)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Competetive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fellowships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=35)),
                ('eligibility', models.TextField()),
                ('location_and_format', models.CharField(max_length=100)),
                ('university_organization', models.CharField(max_length=100, null=True)),
                ('funding', models.CharField(max_length=10, null=True)),
                ('benifits', models.TextField()),
                ('date_of_expiry', models.DateField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('referral_link', models.CharField(max_length=150)),
                ('link_to_apply', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hackathons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hosted_by', models.CharField(max_length=50)),
                ('eligibility', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('topics', models.CharField(max_length=150)),
                ('format', models.CharField(max_length=50)),
                ('prize_money_description', models.TextField(blank=True)),
                ('link_to_apply', models.CharField(blank=True, max_length=150)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('comapny_org', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('registration_open', models.DateField()),
                ('registration_close', models.DateField()),
                ('eligibility', models.TextField()),
                ('referral_link', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Medical and Para-medical', 'Medical and Para-medical'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Law', 'Law'), ('Sciences', 'Sciences')], default='Everyone', max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('email', models.EmailField(max_length=254)),
                ('linked_in', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Scolarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('eligibility', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('university_organization', models.CharField(max_length=100, null=True)),
                ('stipend', models.CharField(max_length=80)),
                ('duration', models.CharField(max_length=80)),
                ('end_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Medical and Para-medical', 'Medical and Para-medical'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Law', 'Law'), ('Sciences', 'Sciences')], default='Everyone', max_length=50)),
                ('referral_link', models.CharField(max_length=150, null=True)),
                ('link_to_apply', models.CharField(max_length=150)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
