# Generated by Django 4.0 on 2022-01-19 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.CharField(max_length=10)),
                ('requirements', models.CharField(max_length=50)),
                ('referral_link', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=150)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Competetive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fellowships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tenure', models.CharField(max_length=15)),
                ('eligibility', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=20)),
                ('date_of_expiry', models.DateField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('referral_link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hackathons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('topics', models.CharField(max_length=150)),
                ('hosted_by', models.CharField(max_length=50)),
                ('application_link', models.CharField(max_length=150)),
                ('format', models.CharField(max_length=50)),
                ('prize_money', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Scolarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('eligibility', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('stipend', models.CharField(max_length=10)),
                ('end_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
