# Generated by Django 4.0 on 2022-01-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_hackathons_link_to_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathons',
            name='application_link',
        ),
        migrations.RemoveField(
            model_name='hackathons',
            name='prize_money',
        ),
        migrations.AddField(
            model_name='hackathons',
            name='eligibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hackathons',
            name='prize_money_description',
            field=models.TextField(blank=True),
        ),
    ]
