# Generated by Django 4.0 on 2022-01-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_certifications_competetive_fellowships_hackathons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='duration',
        ),
    ]
