# Generated by Django 4.0 on 2022-01-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_fellowships_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowships',
            name='format',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='fellowships',
            name='tenure',
            field=models.CharField(max_length=35),
        ),
    ]
