# Generated by Django 4.0 on 2022-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_fellowships_format_alter_fellowships_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='scolarships',
            name='referral_link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
