# Generated by Django 4.0 on 2022-01-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_internship_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='event_host',
            new_name='comapny_org',
        ),
    ]
