# Generated by Django 4.0 on 2022-04-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_internship_multibranch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='multibranch',
        ),
    ]
