# Generated by Django 4.0 on 2022-04-08 15:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_remove_internship_branch_internship_multibranch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scolarships',
            name='branch',
        ),
        migrations.AddField(
            model_name='scolarships',
            name='multibranch',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Medical and Para-medical', 'Medical and Para-medical'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Law', 'Law'), ('Sciences', 'Sciences'), ('Pharmacy', 'Pharmacy'), ('Nursing', 'Nursing'), ('Everyone', 'Everyone')], default='Everyone', max_length=117),
        ),
    ]
