# Generated by Django 4.0 on 2022-04-28 18:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_remove_scolarships_branch_scolarships_multibranch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scolarships',
            name='multibranch',
        ),
        migrations.AddField(
            model_name='scolarships',
            name='branch',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Medical and Paramedical', 'Medical and Paramedical'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Law', 'Law'), ('Sciences', 'Sciences'), ('Pharmacy', 'Pharmacy'), ('Nursing', 'Nursing'), ('Everyone', 'Everyone')], default='Everyone', max_length=50),
        ),
        migrations.AlterField(
            model_name='internship',
            name='multibranch',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Medical and Paramedical', 'Medical and Paramedical'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Law', 'Law'), ('Sciences', 'Sciences'), ('Pharmacy', 'Pharmacy'), ('Nursing', 'Nursing'), ('Everyone', 'Everyone')], default='Everyone', max_length=116),
        ),
    ]
