# Generated by Django 4.0 on 2022-05-22 20:40

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_remove_scolarships_multibranch_scolarships_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('comapny_org', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('Package', models.CharField(max_length=80)),
                ('format', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('registration_open', models.DateField()),
                ('registration_close', models.DateField()),
                ('eligibility', models.TextField()),
                ('referral_link', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('multibranch', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Medical and Paramedical', 'Medical and Paramedical'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Law', 'Law'), ('Sciences', 'Sciences'), ('Pharmacy', 'Pharmacy'), ('Nursing', 'Nursing'), ('Everyone', 'Everyone')], default='Everyone', max_length=116)),
            ],
        ),
    ]
