# Generated by Django 4.0 on 2022-05-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_rename_title_careerful_corporate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerful',
            name='registration_open',
            field=models.DateField(blank=True),
        ),
    ]
