# Generated by Django 4.0 on 2022-05-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_alter_careerful_registration_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerful',
            name='registration_open',
            field=models.DateField(blank=True, null=True),
        ),
    ]
