# Generated by Django 4.0 on 2022-05-30 06:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_alter_careerful_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='brought_to_you_by',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Student Internship Club', 'Student Internship Club'), ('GCGC', 'GCGC'), ('CGC visakhapatnam', 'CGC visakhapatnam'), ('CGC Hyderabad', 'CGC Hyderabad'), ('CGC Bengaluru', 'CGC Bengaluru')], default='Student Internship Club', max_length=74),
        ),
    ]
