# Generated by Django 4.0 on 2022-05-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_alter_internship_brought_to_you_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerful',
            name='brought_to_you_by',
            field=models.CharField(blank=True, choices=[('Student Internship Club', 'Student Internship Club'), ('GCGC', 'GCGC'), ('CGC Visakhapatnam', 'CGC Visakhapatnam'), ('CGC Hyderabad', 'CGC Hyderabad'), ('CGC Bengaluru', 'CGC Bengaluru')], default='Student Internship Club', max_length=70),
        ),
    ]
