# Generated by Django 4.0 on 2022-06-04 08:44

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_careerful_brought_to_you_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship_archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('comapny_org', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('registration_open', models.DateField()),
                ('registration_close', models.DateField()),
                ('eligibility', models.TextField()),
                ('referral_link', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('multibranch', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Medical and Paramedical', 'Medical and Paramedical'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Law', 'Law'), ('Sciences', 'Sciences'), ('Pharmacy', 'Pharmacy'), ('Nursing', 'Nursing'), ('Everyone', 'Everyone')], default='Everyone', max_length=116)),
                ('brought_to_you_by', models.CharField(blank=True, choices=[('Student Internship Club', 'Student Internship Club'), ('GCGC', 'GCGC'), ('CGC Visakhapatnam', 'CGC Visakhapatnam'), ('CGC Hyderabad', 'CGC Hyderabad'), ('CGC Bengaluru', 'CGC Bengaluru')], default='Student Internship Club', max_length=70)),
            ],
        ),
    ]
