# Generated by Django 4.0 on 2022-07-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_internship_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerful',
            name='package',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
