# Generated by Django 4.0 on 2022-12-28 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0024_internship_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='registered',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
