# Generated by Django 4.0 on 2022-04-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_link',
            new_name='event_link_OR_registration_link',
        ),
        migrations.AddField(
            model_name='event',
            name='event_registration',
            field=models.CharField(choices=[('Registration Link', 'Registration Link'), ('Recording Link', 'Recording Link')], default='Recording Link', max_length=50),
        ),
    ]
